---
- name: Docker Compose
  community.docker.docker_compose:
    project_name: node-api
    definition:
      version: "2"
      services:
        app:
          image: {{ "nodezin_image" }}
          restart: always
          command: npm start
          ports:
            - "8000:8080"
          
          
        
