version: "3"

services: 
  app:
    container_name: node-api
    image: yakimura2/nodezin
    restart: unless-stopped
    volumes:
      - .:/usr/app 
    command: npm start
    ports: 
       - "8080:8080"
       
