name: Pull request workflow
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  foldersChanged:
    runs-on: ubuntu-20.04
    steps:
     - id: file_changes
       uses: trilom/file-changes-action@1.2.4

     - name: Get folders
       id: folders
       run: |
        content=$(jq ".[]" $HOME/files.json | grep ".tf" | sed 's/\/[^/]*$/\//' |  sed -e 's/^"//' -e 's/"$//' | grep -v '\..*' | uniq | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=folders::$content"
    outputs:
      folders: ${{ steps.folders.outputs.folders }}
  
  TFLint:
    runs-on: self-hosted
    needs: foldersChanged
    name: TFLint
    if: ${{ needs.foldersChanged.outputs.folders != '[]' && needs.foldersChanged.outputs.folders != '' }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.foldersChanged.outputs.folders) }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Create tflint file
        id: step_one
        run: |
          printf 'config {
            module = true
            force = false
            disabled_by_default = true
          }
          plugin "aws" {
            enabled = true
            version = "0.13.0"
            source  = "github.com/terraform-linters/tflint-ruleset-aws"
          }
      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}
          
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}     
           
      - uses: actions/setup-node@v2
        name: setup node
        with:
          node-version: "14"

      - name: run TFLint
        run: |        
          gh auth login --with-token --git-protocol "https" <<< ${{ secrets.GITHUB_TOKEN }}
          gh auth setup-git
          cp .tflint.hcl ${{ matrix.folder }}
          cd ${{ matrix.folder }}
          tflint --init
          tfswitch
          /home/runner/bin/terraform get
          tflint -f compact -c .tflint.hcl

  fmt:
    runs-on: ubuntu-20.04
    needs: foldersChanged
    name: fmt
    if: ${{ needs.foldersChanged.outputs.folders != '[]' && needs.foldersChanged.outputs.folders != '' }}
    strategy:
      matrix:
        folder: ${{ fromJson(needs.foldersChanged.outputs.folders) }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: hashicorp/setup-terraform@v1
        name: setup terraform
        with:
          terraform_version: 1.0.0

      - name: run terraform fmt
        run: |
          cd ${{ matrix.folder }}
          terraform fmt -check=true -diff
          
  commitLint:
    runs-on: ubuntu-20.04
    needs: [TFLint, fmt]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v4
