name: Pull request workflow
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:  
  TFLint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
          os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: hashicorp/setup-terraform@v1
        name: setup terraform
        with:
          terraform_version: 1.0.0

      - name: run TFLint
        run: |
          cp .tflint.hcl ~/.tflint
          tflint --version
          tflint --init
          terraform get
          tflint -f compact -c .tflint.hcl

  fmt:
    runs-on: ${{ matrix.os }}
    needs: [TFLint]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - uses: hashicorp/setup-terraform@v1
        name: setup terraform
        with:
          terraform_version: 1.0.0

      - name: run terraform fmt
        run: |
          terraform fmt -check=true --recursive
          
  commitLint:
    runs-on: ${{ matrix.os }}
    needs: [TFLint, fmt]
    if: |
      always() &&
      !contains(needs.*.result, 'failure') &&
      !contains(needs.*.result, 'cancelled')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: wagoid/commitlint-github-action@v4
